language: go
go:
  - 1.10.x
install: true
before_script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
script: 
  - go build 
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
notifications:
  email: false
